### ISSUE TITLE
[BUG] no Longer works

### ISSUE THREAD

**Issue by allanlaal** [avallete/yt-playlists-delete-enhancer#155]
**Steps to reproduce**:

install TamperMonkey or similar
install from https://github.com/avallete/yt-playlists-delete-enhancer/raw/gh-pages/yt-playlists-delete-enhancer.user.js
go to https://www.youtube.com/playlist?list=WL

**Expected results**:

every video has a delete button on its row

**Actual results**:

none

**Notes**:

Firefox 101. used to work before (pretty sure it was this userscript)

**Comment by avallete** [comment]
Hi there,

There is only a global remove button, in the screenshot the cross and circles are only here to show which videos would be deleted / kept in the playlist depending on the "percent of viewing" parameter.

Could be worth to have some kind of visulatization with the plugin itself tough.
