### ISSUE TITLE
[BUG] Youtube update prevents this script's interface from loading (Script no longer works)

### ISSUE THREAD

**Issue by honem** [avallete/yt-playlists-delete-enhancer#170]
**Steps to reproduce**:
* Have Tampermonkey installed , install this script
* Go to any Playlist page

**Expected results**:
* Interface for this script appears
* Along with the button to remove watched youtube videos from that playlist

**Actual results**:
* Large rectangular UI element added by Youtube is now there
* Interface and button is nowhere to be seen

**Notes**:

**Comment by honem** [comment]
https://github.com/Elijas/auto-youtube-subscription-playlist-2/blob/master/removeVidsFromPlaylist.md

has javascript code that appears to work for removing watched videos from a playlist

Posting this just in case it helps in tracking down where the issue is by posting code that does work. I'm aware there's different languages involved but I feel it may help you anyways

**Comment by avallete** [comment]
Should be fixed in 1.5.10

**Comment by Haeherfeder** [comment]
@honem could you contact me? (sorry that i ask here, but i didn't find another way to do it)
