### ISSUE TITLE
[FEAT] Ajouter les boutons "remove" et "add to playlist" sous les éléments de la playlist en cours de lecture

### ISSUE THREAD

**Issue by freMea** [avallete/yt-playlists-delete-enhancer#196]
Salut,

Je suis tombé sur ton script en cherchant à en créer un moi-même pour rendre les fonctionnalités "remove" et "add to playlist" des vidéos de la playlist en cours plus accessibles.

![image](https://user-images.githubusercontent.com/22337329/202873341-0e0423fa-61d5-4b79-94df-4e7fb0b114e0.png)

Ces fonctionnalités sont actuellement dans un menu. C’est très pénible quand on veut rapidement supprimer plusieurs vidéos ou les ajouter dans une playlist. La capture d’écran montre l’espace où ces deux boutons pourrait être déplacés.

Via l’inspecteur du devtools, vu la façon dont YT a construit sa webapp, je ne comprends pas comment je pourrais faire. Je ne trouve pas quelles fonctions sont envoyées. D’après ton code, il semble que le plus simple soit d’utiliser l’API de youtube. Je vais voir ça. Peut-être que cette fonctionnalité pourrait être implémentée si ça te parait opportun.

**Comment by avallete** [comment]
Salut,

C'est pas la première fois que j'ai cette demande effectivement. Je suis pas sûr a quel point ça peut se faire pour la partie 'save to playlist' mais la partie 'remove from playlist' devrais pouvoir s'intégrer assez facilement. Je regarderais ça lorsque j'aurais un peu de temps.

**Comment by avallete** [comment]
J'ai mis en place la fonction de "quick remove", dispo dans la version 1.6.0 du script. Je n'ai pas setup la fonction "sauve to playlist", je veux garder le script uniquement scopé au "cleanup de playlist".

**Comment by freMea** [comment]
Pas de souci. La suppression est ce que j’utilise le plus. Malheureusement, le bouton de suppression n’apparait pas sur la playlist en cours de lecture, celle à droite du player.
![image](https://user-images.githubusercontent.com/22337329/204163563-df34786e-f46e-48d8-b639-73db57738bc0.png)

La fonction n’est active que sur les adresses `https://www.youtube.com/playlist?list=…` Ce qui est toujours ça mais est redondant avec la fonction remove selon le watchtime déjà présente dans la même fenêtre. C’est surtout le premier cas d’utilisation qui m’intéressait.

**Comment by datspike** [comment]
> J'ai mis en place la fonction de "quick remove", dispo dans la version 1.6.0 du script. Je n'ai pas setup la fonction "sauve to playlist", je veux garder le script uniquement scopé au "cleanup de playlist".

Thanks for introducing this. It's a great feature, however pressing the button makes the page reload for me (thus I'm losing my scroll position on the page)
After commenting the reload line in the `decrementNumberOfVideosInPlaylist` function the script seems work perfectly normal

**Comment by avallete** [comment]
> > J'ai mis en place la fonction de "quick remove", dispo dans la version 1.6.0 du script. Je n'ai pas setup la fonction "sauve to playlist", je veux garder le script uniquement scopé au "cleanup de playlist".
> 
> Thanks for introducing this. It's a great feature, however pressing the button makes the page reload for me (thus I'm losing my scroll position on the page) After commenting the reload line in the `decrementNumberOfVideosInPlaylist` function the script seems work perfectly normal

I know that I have introduced a "reload" when some change raise an exception for some reason (missing elements in the page). Could you git me some details:

- Did you navigate on the "app" before accessing to the playlist, or did you load the page on the playlist URL right away ?
- Does the playlist is "Watch later" or is it another custom playlist ?

**Comment by datspike** [comment]
> * Did you navigate on the "app" before accessing to the playlist, or did you load the page on the playlist URL right away ?
The page reloads itself in both scenarios
> * Does the playlist is "Watch later" or is it another custom playlist ?
The page reloads while clicking the delete button on any playlist available including Watch Later
