### ISSUE TITLE
Video removal from playlist not permanent.

### ISSUE THREAD

**Issue by rangervaloy** [avallete/yt-playlists-delete-enhancer#212]
Today (3/14/23) I started noticing that removing either with the Remove! button or the red trashcan appears to work, but when the playlist list refreshed the videos show up again.  Using version 1.6.0, which appears to the latest release.

**Comment by rangervaloy** [comment]
The version of Chrome where it is not working is:  111.0.5563.65 (Official Build) (64-bit)

**Comment by avallete** [comment]
I haven't been able to reproduce on chrome `Version 111.0.5563.110 (Official Build) (arm64)`

I'm wondering if any other plugin you have might be conflicting with the behaviour of this script. Can you try it on a session without any plugins ?

**Comment by rangervaloy** [comment]
Well, I tested it on another computer, and it works.  Apparently my company did something to my work laptop that prevents it from working correctly for Chrome.  Any idea how I diagnose this?  Perhaps send you a log?  Maybe something can be done to get around it.  The fact that script still works for Firefox may be clue.  Thanks.

**Comment by rangervaloy** [comment]
OK, reset chrome, and now it works.  I had assume that chrome settings were synchronized, and anything that worked in one computer would also work on other.  Obviously thats not the case!

Thanks for looking into it.  Next time I'll reset chrome before opening a bug report.
