### ISSUE TITLE
[BUG]Cannot read properties of undefined (reading 'response')

### ISSUE THREAD

**Issue by water903** [avallete/yt-playlists-delete-enhancer#228]
**Steps to reproduce**:
YouTube: Home Click Watch later

**Expected results**:
Normal appearance
**Actual results**:
appearance"Cannot read properties of undefined (reading 'response')"
![2024-3-25 14-49-39](https://github.com/avallete/yt-playlists-delete-enhancer/assets/39816578/2c890829-ac68-48eb-a355-81e7cc4651e0)

**Notes**:
chrome 123.0.6312.59

**Comment by avallete** [comment]
I cannot reproduce on my end, from the error message I guess the issue come from this line: https://github.com/avallete/yt-playlists-delete-enhancer/blob/52cb5ab59fe2764b02f862743a3b605cbbda723d/src/yt-api.ts#L116

Maybe you could try to tamper the script to `console.log` what's "reponse" is and what `await response.json()` yield.

**Comment by water903** [comment]
https://github.com/avallete/yt-playlists-delete-enhancer/pull/226
I follow this. It working.

**Comment by AlexBilozir** [comment]
I have this bug in 1.7.1 version

**Comment by AlexBilozir** [comment]
<img width="2555" alt="Смотреть позже - YouTube 2024-06-04 15-29-12" src="https://github.com/avallete/yt-playlists-delete-enhancer/assets/8397468/316ff2a0-6f61-4c67-b99b-5991abe41040">
<img width="2547" alt="Смотреть позже - YouTube 2024-06-04 15-32-42" src="https://github.com/avallete/yt-playlists-delete-enhancer/assets/8397468/e6b4965f-4cfc-4754-aab7-3f4e93008c6d">

I suspect that this is the reason. tried to disable all adblocks and other extensions related to YouTube, but still this error.
