### ISSUE TITLE
Watched videos on longer playlists not being removed

### ISSUE THREAD

**Issue by SidGauVic** [avallete/yt-playlists-delete-enhancer#4]
Since Youtube stopped allowing auto adding of videos to the Watch Later playlist, I've been adding new videos to a separate playlist. When the playlist gets longer and some of the watched videos are on continuation pages, those watched videos are not being removed. I've tried manually scrolling down to load all videos of the playlist, but they still aren't being removed.

The playlist in question has about 300 videos in it, so I'm wondering if there is a limit to how many videos are being checked for removal.

**Comment by avallete** [comment]
I think it’s related to a recent (less than a week ago) YouTube api change (see #5) who make the script cannot delete videos.

I going to need some time to fix that (I’ll try to fix it this or next weekend).

Usually the script should retrieve all the data from your playlist before deleting the videos (however, I didn’t try it with 300+ videos). If the fix next week doesn’t resolve your issue, I’ll look into that, it’s possible that YT also changed the API who allowed me to retrieve this data.

However, I remember also experienced some “glitch” on deleting videos as well in the past, but wasn’t able to reproduce the bug consistently. So once the issue #5 fixed, if you’re still experiencing this bug consistently I would like to have a link to your playlist (to duplicate it debugging).

**Comment by SidGauVic** [comment]
Sounds good. Let me know whenever you need the playlist!

**Comment by avallete** [comment]
After further investigations, I confirm that the way YT internally deal with long (100+) playlists have changed.

I'm working on a fix following #5. I'll make a release addressing this issue before week end.
