### ISSUE TITLE
[BUG] Double remove button

### ISSUE THREAD

**Issue by avallete** [avallete/yt-playlists-delete-enhancer#9]
When performing some specific navigation combination, it duplicates the remove button.

To reproduce:

1. Go to a playlist page, click on a video and start watching.
2. Use browser "previous" button to go back on the playlist page.
3. Button is duplicated.

**Comment by dnicolson** [comment]
The cause seems to be that the `locationchange` event is being invoked an additional time, dispatched here:
https://github.com/avallete/yt-playlists-delete-enhancer/blob/34826cb3b90bae5c0acaccb0051dc01c5b55437d/yt-playlists-delete-enhancer.js#L275

**Comment by avallete** [comment]
Nice spot !

But I do recall that I needed because without it, when navigating from YT pages to "playlist video" pages, the button wouldn't appear (because GreaseMonkey scripts didn't notice an URL change) unless you reload the page. Also, YT had multiples different "events" to describe a "page change" depending on where you came from and which state the app is (ex: user is playing a video or not).

But the way the "navigation watching" are handled by my script (global events listener) is not really reliable, kind of messy and prone to race conditions. There is for sure a better way to do it, just cannot really figure it out yet.
